### ISSUE TITLE
Warp Pads v1.2.2

### ISSUE THREAD

**Issue by SmoochyPit** [mc-datapacks/review-tracker#12]
Project Page: https://github.com/SmoochyPit/Warp-Pads/tree/review
(link edited to be review branch)

**Comment by EstEarth202** [comment]
@SmoochyPit 
- Certified Compatibility :x: 
- Stamp of Quality :x: 

### Advancement

**data\global\advancements\smoochypit\warppads.json**
You can create this advancement anywhere, as long as you don't pollute `/data/global/advancements/folder`.
Usually at `data\warppad\advancements`

### Global ignore

**data\warppad\functions\warpmod.mcfunction**
All `kill @e` miss `!global.ignore` + `!global.ignore.kill`
`title @a[distance=..8]` miss globa.ignore.gui

**data\warppad\functions\creation\newanim.mcfunction**
All `kill @e` & `execute as @e[scores={wp.spawnAnim=99}] run kill @s` miss `!global.ignore` + `!global.ignore.kill`

miss `!global.ignore`
> scoreboard players add @e[scores={wp.spawnAnim=1..}] wp.spawnAnim 1
> scoreboard players set @e[scores={wp.spawnAnim=100..}] wp.spawnAnim 0
> execute as @e[scores={wp.spawnAnim=1..98}]
> execute as @e[scores={wp.spawnAnim=1..}]
> All as @e[distance=..0.5,type=item
> execute as @e[scores={wp.spawnAnim=99}]

After this only `!global.ignore` missing
**data\warppad\functions\1t.mcfunction**
```
scoreboard players add @e[type=item] wp.spawnAnim 0
All three execute as @e[scores={wp.spawnAnim=0}
```
**data\warppad\functions\prewarp.mcfunction**
```
scoreboard players reset @e[tag=!wp.passenger] wp.passXoffset
scoreboard players reset @e[tag=!wp.passenger] wp.passZoffset
```

### More advice
(This section doesn't affect the review. But I recommended to do to increase optimize.)

**data\warppad\functions\creation\del.mcfunction**
```
execute as @e[tag=wp.pad1] at @s unless block ~ ~-1 ~ gold_block run function <...>
     function <...>
                    ├ function < 1 >
                    ├ summon item ~ ~-1 ~ {Ta................
                    ╰ function < 2 >

    function < 1 >
                    ├ particle witch ~ ~-1 ~ 0 0 0 0.5 25
                    ├ forceload remove ~ ~ 
                    ├ execute unless score @s wp.streamFreq matches 0
                    ├ execute unless score @s wp.streamFreq matches 0
                    ╰ execute unless score @s wp.linkedUUID matches 0
    function < 2 >
                    ├ data modify entity @e[tag=wp.maindrop
                    ╰ kill @s
```
As an example, you can reduce a lot of `execute as @e[tag=wp.pad1]`.
This can be done with `wp.pad2` & `wp.pad3` as well.
The function <...> (gold_block, emerald_block, diamond_block) of all three tags can be used together with functions <1> and <2> because their commands are the same.

**data\warppad\functions\cosmetics.mcfunction**
```
execute as @e[tag=wp.locIcon,tag=!wp.selCastIcon,distance=..5] run function <...>
     function <...>
                    ├ execute at @s[scores={wp.iconColor=0}] run particle ...
                    ├ execute at @s[scores={wp.iconColor=1}] run particle ...

```
And there are 3 more files that look like I was told. The example given should help you do the remaining 3 files.
**data\warppad\functions\iterate.mcfunction**
**data\warppad\functions\prewarp.mcfunction**
**data\warppad\functions\warpmod.mcfunction**

If you have any problems or wonder anything, you can comment or DM me discord.

**Comment by SmoochyPit** [comment]
I read through your feedback and fixed what I needed to fix. I also implemented your suggested optimizations on functions where I could. Would you mind taking a look at the updated version? https://github.com/SmoochyPit/Warp-Pads/releases/tag/v1.2.2-beta3

Thank you!

**Comment by oOBoomberOo** [comment]
Mind if I suggest something? Since you're using github you can use the branching feature to make a temporary review branch so that you don't have to release a new version every time there's a review.

**Comment by SmoochyPit** [comment]
Will do! ~~A bit late to do now, but in the future I will do that. Thanks for the suggestion.~~ I have done this and edited my top comment. I'm learning how git and GitHub work, and this is a much better way of doing this, so thank you.

**Comment by oOBoomberOo** [comment]
@EstEarth202 you still working on this?

**Comment by EstEarth202** [comment]
@oOBoomberOo  Yes, I'm teaching him step-by-step in DM because he's new and wants to learn.

**Comment by EstEarth202** [comment]
- Certified Compatibility:heavy_check_mark:
- Stamp of Quality :two_hearts:
- And LMAO Datapack reviewer @EstEarth202. :thumbsup: 
You are the first person I can fully teach. And be the first to get LMAO from me.
