### ISSUE TITLE
Kat's Lightsabers

### ISSUE THREAD

**Issue by kgscialdone** [mc-datapacks/review-tracker#14]
Project Page: https://www.planetminecraft.com/data-pack/kat-s-lightsabers/

**Comment by ghost** [comment]
@KatrinaKitten 
- Certified Compatibility ❌
- Stamp of Quality ❌

Really really good datapack. I have to say it's also really optimized. But due to distracting mistakes it can't be certified.
That's why:

### Custom Model Data ID Convention:
You missed the ID. You used 623 as id, while yours is 632. Ask Boomber, he will certain help you to change it into the one you used.

### Common Traits Convention:
In your ctc tags you set from tag and then id or traits tag. You should set both.
Here's an example:
`/give @s diamond{ctc: {traits: {"some": 1b, "trait": 1b, "here": 1b}, id: "example", from: "convention:wiki"}}`

I'm sure you won't use so much to correct these small problems. Bye

**Comment by kgscialdone** [comment]
Thanks for reviewing this! I'll get the model data issue sorted out ASAP. 

However, I'm not sure what you mean with regards to the CTC stuff. There are plenty of places I only _check_ for either ID or traits, but the only places I actually create items (other than internal stuff the user shouldn't have access to) are in loot tables, and I'm 100% sure I didn't miss either for any items in those. Could you elaborate on where exactly this was?

**Comment by kgscialdone** [comment]
My custom model ID has been changed in registry as appropriate =)

I've also double checked my CTC and confirmed that, as previously mentioned, I create no items that do not have both an ID and traits, except for the Saber Forge display model (which is completely inaccessible in an armor stand's head slot and as such has neither).

**Comment by ghost** [comment]
Datapack Verified

- Certified Compatibility✔️
- Stamp of Quality 💕
