### ISSUE TITLE
EnderChest+

### ISSUE THREAD

**Issue by rx-dev** [mc-datapacks/review-tracker#18]
Project Page: https://github.com/RitikShah/EnderChestPlus/releases/

Expandable EnderChest. Requires a lib PlayerDB. It should be mostly fine, not sure where it would fail.
I hope I don't need any other info here?

**Comment by EstEarth202** [comment]
@RitikShah 

- Certified Compatibility ✅
- Stamp of Quality ✅

# Everything is fine and ok. 
# Status: Waiting for review MC-PlayerDB
## But there are some things I think you should do.

- [ ] remove unuse `rx` folder.
- [ ] Request review pack MC-PlayerDB too.
 ### Note
**_In order to complete the certification_**, because your pack needs to use some `function` and `yellow_shulker_box loot_table` from it.
So you need to get both packs to certified first.
Then I'm going to close this review and announce both packs in the `✅certified channel` and give roles.

### You can request review in the comment below and ✅ list if you have done it.

**Comment by rx-dev** [comment]
I have an unused function `rx:random`, but I do need the rx folder for the item tag, `rx:all`. I plan to use `rx` namespace for all my datapacks and somethings are generic so they will often land in the same spot.

**Comment by rx-dev** [comment]
I plan on using Lantern Load again (uses the `load` scoreboard) which wouldn't allow you to certify my datapack, so I think it's best to close this.
