### ISSUE TITLE
Rotation Wrench

### ISSUE THREAD

**Issue by mainrs** [mc-datapacks/review-tracker#25]
Project Page: https://github.com/vanilla-friendly-datapacks/rotation-wrench

**Comment by EstEarth202** [comment]
@SirWindfield 

- Certified Compatibility ❌
- Stamp of Quality ❌
- Final comment after closed verified.

## Certified Compatibility part

### Namespace Convention

`zerotask\functions\rotation_wrench\private\raycast\start_ray.mcfunction` tag `raycasting_wrench` doesn't follow.

## Stamp of Quality part
If you just want Certified Compatibility You can skip this part.

### Datapack Uninstallation missing

## Technical Advice Commentary part

`zerotask\functions\rotation_wrench\private\raycast\hit_block.mcfunction` You don't need to `execute run`, just `function <...>`.

`zerotask\functions\rotation_wrench\private\replace_blocks\switch.mcfunction` You don't need to `execute as @s run`, just `tag @s remove`

Since all 3 files have the same tag conditions, repeatedly checking for the same conditions affects performance.

> zerotask\functions\rotation_wrench\private\replace_blocks\facing.mcfunction
> zerotask\functions\rotation_wrench\private\replace_blocks\glazed_terracotta.mcfunction
> zerotask\functions\rotation_wrench\private\replace_blocks\logs.mcfunction

This is what I recommend.
Example: 
```
execute if block ~ ~ ~ #minecraft:logs run function zerotask:rotation_wrench/private/replace_blocks/tag_check
execute if block ~ ~ ~ #zerotask:rotation_wrench/facing run function zerotask:rotation_wrench/private/replace_blocks/tag_check
execute if block ~ ~ ~ #zerotask:rotation_wrench/glazed_terracotta run function zerotask:rotation_wrench/private/replace_blocks/tag_check

Inside tag_check

execute as @s[tag=!zerotask.preventWrenchBlockRotationRecursion] run function <...>
execute as @s[tag=zerotask.preventWrenchBlockRotationRecursion] run function <...>
```

**Comment by mainrs** [comment]
Updating the repository to include the changes you suggested under the certified compatibility part and the stamp of quality part.

**Comment by EstEarth202** [comment]
- Certified Compatibility:heavy_check_mark:
- Stamp of Quality :two_hearts:
- And LOL Datapack reviewer @EstEarth202. :thumbsup:
