### ISSUE TITLE
Phantoms are weak against spectral

### ISSUE THREAD

**Issue by mainrs** [mc-datapacks/review-tracker#26]
Project Page: https://github.com/vanilla-friendly-datapacks/phantoms-are-weak-to-spectral

Literally only one advancement and a trigger function, would be surprised if something isn't in order. Now I jinxed it though...

**Comment by EstEarth202** [comment]
@SirWindfield 

- Certified Compatibility ❌
- Stamp of Quality ❌
- Final comment after closed verified.

## Certified Compatibility part

### Global Ignoring tag

`zerotask\functions\phantoms_are_weak_to_spectral\private\kill_phantom.mcfunction` -> `tag=!global.ignore,tag=!global.ignore.kill` missing

## Stamp of Quality part
If you just want Certified Compatibility You can skip this part.

### Datapack Uninstallation

Because your pack doesn't need to be uninstalled. But you have to tell the user why this pack doesn't need to be uninstalled.

**Comment by mainrs** [comment]
I've pushed a new commit to the repository that should fix the issues mentioned here :) Thanks for the review.

**Comment by EstEarth202** [comment]
- Certified Compatibility:heavy_check_mark:
- Stamp of Quality :two_hearts:
- And LMAO Datapack reviewer @EstEarth202. :thumbsup:
