### ISSUE TITLE
Beacon Shulker

### ISSUE THREAD

**Issue by mainrs** [mc-datapacks/review-tracker#30]
Project Page: https://github.com/vanilla-friendly-datapacks/beacon-shulker

**Comment by ghost** [comment]
**Beacon Shulker** by SirWindfield
✔️Certified Datapack
✔️Stamp of Quality

✅You can now use [Certified Datapack+Stamp of Quality Banner](https://i.imgur.com/ltLPoQp.png) in the datapack description/wiki/download page etc.

Nice datapack. Also, since it doesn't use any @e or @a , it is really optimized and easy to review.

Only one thing about compatibility: it would be better using zt.bsc scoreboard instead of bsc. But it still is compliant with the conventions, so don't worry and you are not forced to update the datapack.
Other thing: there is a useless `as @s` in the on_shulker_place.mcfunction file.

**Comment by mainrs** [comment]
> Only one thing about compatibility: it would be better using zt.bsc scoreboard instead of bsc. But it still is compliant with the conventions, so don't worry and you are not forced to update the datapack.

True, I will add it to the list of stuff I need to change :3 ty for the review
