### ISSUE TITLE
Brewing stands keeps fuel

### ISSUE THREAD

**Issue by mainrs** [mc-datapacks/review-tracker#31]
Project Page: https://github.com/vanilla-friendly-datapacks/brewing-stand-keeps-fuel

**Comment by ghost** [comment]
**Brewing stands keeps fuel** by SirWindfield
✔️Certified Datapack
✔️Stamp of Quality

✅You can now use Certified Datapack+Stamp of Quality Banner in the datapack description/wiki/download page etc.

-I suggest you to check the limit=1 in the only @e selector inside tick.mcfunction and test if it works also if more than one brewing stands are dropped in different places. I'm not sure it will work, but it could
-Placing a sign in ~ 255 ~ is a good way, but also could place it in a different and far chunk, like 829999 0 829999 (this is where I place barrels or shulker box for inventory manipulation, signs for special text etc. but 82 is my number).
It could be a problem for optimization, since you need to /forceload the chunk in the load function, but you will not destroy a block of the probable skyscraper the player built.

Nice and useful datapacks, like the others. 😉 Bye!
