### ISSUE TITLE
Homes Enhanced - Just Another Homes Datapack

### ISSUE THREAD

**Issue by Gnottero** [mc-datapacks/review-tracker#36]
Project Page: https://www.planetminecraft.com/data-pack/homes-enhanced-just-another-homes-datapack/

**Comment by EstEarth202** [comment]
- Certified Compatibility ❌
- Stamp of Quality 💕

### Common Trait Convention ☑️
### Custom Model ID ☑️
### Global ignoring tag ❌

> `gnottero\functions\homes_enhanced\main`  
> `execute as @a[tag=!global.ignore.pos, tag=!global.ignore]` 
> Here you don't have to use global ignore tag since I checked all the operations.
> `tag=!global.ignore` **This tag does not apply to player-only selectors (@ a, @ e[type=player], @ p, etc.)**
### Global Durability ☑️
### Namespace Convention ✔️
### Shulker Box Loot Table ☑️
### Datapack Advancement ✔️
### Datapack Uninstallation ✔️
### Reloading Message ✔️

### Tecnical advice

**Did you know**: `fake_player` doesn't need to use namespace because it is already inside the objective namespace. `#dest_infos gn.dest_infos`

### Note
✔️ = Followed
❌ = Doesn't follow
☑️ = Not required/Skip

**Comment by Gnottero** [comment]
Okay, I should have that fixed. Could you please check it out?
You can also find the datapack on github at this link:
https://github.com/Gnottero/Homes-Enhanced

**Comment by EstEarth202** [comment]
- Certified Compatibility:heavy_check_mark:
- Stamp of Quality :two_hearts:
- And Good pack, LOL Datapack reviewer @EstEarth202. :thumbsup:
