### ISSUE TITLE
Player Head Dragon

### ISSUE THREAD

**Issue by asdru22** [mc-datapacks/review-tracker#37]
Project Page: <https://www.planetminecraft.com/data-pack/player-head-dragon/>

its not a big datapack but I'm interested in seeing if everything has been fully optimized

**Comment by ghost** [comment]
❌Certified Datapack
❌Stamp of Quality

**data\dragon\functions\summon.mcfunction**
kill @e[type=item,distance=0] -> kill @e[type=item,tag=!global.ignore,tag=!global.ignore.kill,distance=0]
Who knows, coincidences are possible. Or someone could make a datapack that attaches items to some entities, and it could work also for your small bat.
**CustomModelData:1005?** I suggest you to read the Custom Model Data convention. Anyway, it will pass, since the item is used for less than a tick and you do not change the model in any way. It's not a problem for compatibility.
**DP Advancement Convention**
You don't need to follow this convention, but you should if you also want the Stamp of Quality.
https://mc-datapacks.github.io/en/conventions/datapack_advancement.html
**Remove the reload message**

Text here when you did.
Nice and optimised datapack, _I suggest you to use small armor stands instead big ones._

**Comment by asdru22** [comment]
Ok i think i fixed everything, even added the advancements

**Comment by ghost** [comment]
✔️Certified Datapack
✔️Stamp of Quality

Totally useless, but really nice. I like it (I know you know)
You can now use this banner on datapack description/download page/wiki:
https://i.imgur.com/ltLPoQp.png
