### ISSUE TITLE
S.E.A.T Pack - Sit anywhere in Minecraft

### ISSUE THREAD

**Issue by x-2mas** [mc-datapacks/review-tracker#50]
Project Page: [Planet Minecraft](https://www.planetminecraft.com/data-pack/s-e-a-t/)

**Notes:**
- I adapted the pack to the official guidelines given [here](https://mc-datapacks.github.io/en/index.html)
- This datapack is conceptually simple but maybe difficult to review since I tried building it around a 'framework' of my own. 😅
- Once downloaded, you should see the pack is a combination of two datapacks - S.E.A.T and C.O.R.E.
- The C.O.R.E pack is a 'framework' I made to re-use code and prevent conflicts with future packs. 
- The S.E.A.T pack depends on the C.O.R.E pack and the two function together. _You can see why this might make it a little awkward to review._

When it comes to namespaces, I had already implemented a '**x_**' namespace for all pack features before learning about Datapack Conventions. That namespace feels lazy but I chose that in order to fit the scoreboard 16-char limit.  I wish I had used a more verbose namespaces like 'xmas' or 'xms' but I feel its too late to change it now. The C.O.R.E features a backward-compatibility versioning system that might break if I did that.

If you find the code too complex, have a look in the 'scripts' folder where I've commented pretty much every line of code there is. The scripts follow the _mcscript_ syntax found [here](https://mcscript.stevertus.com/). I used _mcscript_ for code organization reasons but it all compiles to .mcfunctions in the end.

If you need anymore help, please reach out to me! 
_Thank You!_ 💛

**Comment by x-2mas** [comment]
So sorry to do this, but I just realized there was some C.O.R.E code that didn't conform to standards. I missed it because I wasn't actively using it in my S.E.A.T pack. 

Should be all updated now! [Download](https://www.planetminecraft.com/data-pack/s-e-a-t/)

Changes:
- Added global.ignore tags to files 
    - tp_kill.mcfunction
    - load_edata.mcfunction
    - attach.mcfunction
- Removed left-over dead code from
    - main.mcfunction
- Also removed some left-over function files

**Comment by x-2mas** [comment]
Alright, the last update I made, which added **global.ignore** tags, ended up breaking mob-riding features _(I made my code ignore its own entities)._ The [latest update](https://www.planetminecraft.com/data-pack/s-e-a-t/) fixes that. 

Changed Files:
- attach.mcfunction

PS: I have a feeling this is going to keep happening. Sorry about that. I'll mention any updates/changes here.

**Comment by EstEarth202** [comment]
# Certified Compatibility ❓
# Stamp of Quality ❓
# 💕━━━━━・Stamp・━━━━━💕
## Datapack Advancement ✔️
I think you put it alternately.
```
"title": "Xmas Labs - S.E.A.T",
            "item": "minecraft:nether_star"
```
```
"title": "Xmas Labs - C.O.R.E",
            "item": "minecraft:saddle"
```
## Datapack Uninstallation  ✔️
## ~~Reloading Message~~ ❓ (Recheck after Tecnical advice fix)
# 🔆━━━━━・Not Force・━━━━━🔆
## Common Trait Convention ☑️
## Global Durability ☑️ 
# ⚠━━━━━・Important ・━━━━━⚠
## Custom Model ID ☑️
## ~~Global ignoring tag~~ ❓(Recheck after Tecnical advice fix)

## Namespace Convention ❌
- [x] ❌Storage namespace `data modify storage x_core`
For `storage`, if the game doesn't find a colon, the game will see namespace `minecraft:x_core`. For which you need to use x_core: ...
![aTxPsqJDRj](https://user-images.githubusercontent.com/66269767/108766442-be611400-7587-11eb-9b97-8daae8f6a252.png)
## Shulker Box Loot Table ☑️
# 🎯━━━━━・Other ・━━━━━🎯
## Something missing ❓
## Bug report 🐞
# Tecnical advice (⚠Optimization) 🔆

❔ Which you can choose not to do if you want, you can tell me if you want. Because this is not force and does not affect reviews. But the impact on the review will be in an important section 

- [ ] ❌✔️🔆⚠Performance problem⚠

Since you use mcscript to write this pack, you can use it fully. But that's not a problem
But the real problem is with the compile output. Which is technically very detrimental to performance. And as a result, reviewing some points is difficult So I want you to fix this before I add another review.

Your datapack runs multiple lines of commands that have the same conditions. Which I will give a rough example as follows: 

What effect does this have?
It results in When it's done running the first command, it needs to go unnecessarily return to as @selector with the same condition again. 
![Code_-_Insiders_GSVIFdrB7E](https://user-images.githubusercontent.com/66269767/108768536-55c76680-758a-11eb-8eeb-1154d568891a.png)
Instead of 
![Code_-_Insiders_LxZdpthKA7](https://user-images.githubusercontent.com/66269767/108768626-77285280-758a-11eb-9bee-c4adf0232e6c.png)
   ↳ ![Code_-_Insiders_DgGe6xp7BK](https://user-images.githubusercontent.com/66269767/108768642-7db6ca00-758a-11eb-8c2d-85593096376a.png)

There are still a lot of mcfunction files like this. That should be fixed.

If you are looking for a sample data pack in terms of performance and organization of files, folders and commands. I suggest you to watch the work of [Boomber360](https://www.planetminecraft.com/member/boomber360/)

# 📝━━━━━・Note・━━━━━📝
✔️ = Followed
🔆 = Advised to use
❌ = Doesn't follow
❓ =  Doubt / Something missing
☑️ = Not required/Skip
- [ ] = Required -> with ❌ Must do, ✔️ Should do, 🔆 Not force

**Comment by x-2mas** [comment]
Thank you for your review!! I've corrected the **namespace issue** as well as the **advancement item mix-up** (lol). 
**Updated [here](https://www.planetminecraft.com/data-pack/s-e-a-t/).**

As for the last point about optimizing commands, you are absolutely right! Using the same condition prefixes over and over will significantly affect performance. What's funny is that this is the **only** feature of _mcscript_ that I use! It's called **command-grouping** and it converts this:
```
  as('@e[tag=demo]'), if('score @s DEMO matches 1..'){
    /say Demo!
    /say Another Demo!
    /say Another Another Demo!
  }
```
to this:
```
  /execute as @e[tag=demo] if score @s DEMO matches 1.. run say Demo!
  /execute as @e[tag=demo] if score @s DEMO matches 1.. run say Another Demo!
  /execute as @e[tag=demo] if score @s DEMO matches 1.. run say Another Another Demo!
```

As you pointed out, this is indeed very inefficient. As a result, I plan to **completely remove _mcscript_ and rewrite both datapacks using only Minecraft functions.** I have to do this especially since _mcscript_ is no longer being developed and a lot of its features are broken in current versions of Minecraft. 

Unfortunately, I'll only get time to do this when I work on my next datapack (which won't be anytime soon) and since this isn't a requirement for certification, I'm going to leave it like this for now. I hope that's okay? 😅

Thanks again for taking the time to review this! I know this must be a challenge to review so feel free to keep this your _lowest_ priority. :)

**Comment by EstEarth202** [comment]
No problem, you can update your performance whenever you want. After I finished the review When you correct those points, you can checkbox to inform other users who have to see this detail.

**Comment by EstEarth202** [comment]
# Certified Compatibility ❌
# Stamp of Quality ❌
# 💕━━━━━・Stamp・━━━━━💕
## Datapack Advancement ✔️
## Datapack Uninstallation  ✔️
## Reloading Message ❌
# 🔆━━━━━・Not Force・━━━━━🔆
## Common Trait Convention ☑️
## Global Durability ☑️ 
# ⚠━━━━━・Important ・━━━━━⚠
## Custom Model ID ☑️
## Global ignoring tag ❌
-  `global.ignore.kill`✔️

-  `global.ignore.gui`✔️

-  `global.ignore.pos`✔️

- [ ]  `global.ignore` ❌

You don't have a `global.ignore` at `@e` using `score condition`, because score is less clear than `tag` and `nbt`.
Therefore cannot be excluded to not have

```
data\x_core\functions\ticker.mcfunction
data\x_core\functions\scrollbar.mcfunction

data\x_core\functions\rotation_tracking.mcfunction -> Other: `data get entity @s Rotation[X] 1` I see that you put X

data\x_core\functions\manage_eids.mcfunction
data\x_core\functions\manage_attachments.mcfunction
data\x_core\functions\collision_blocking.mcfunction
```

## Namespace Convention ✔️
## Shulker Box Loot Table ☑️
# 🎯━━━━━・Other ・━━━━━🎯
## Something missing ❓
## Bug report 🐞


# 📝━━━━━・Note・━━━━━📝
✔️ = Followed
🔆 = Advised to use
❌ = Doesn't follow
❓ =  Doubt / Something missing
☑️ = Not required/Skip
- [ ] = Required -> with ❌ Must do, ✔️ Should do, 🔆 Not force

**Comment by EstEarth202** [comment]
# Certified Compatibility ❌
# Stamp of Quality ❌
# 💕━━━━━・Stamp・━━━━━💕
## Datapack Advancement ✔️
## Datapack Uninstallation  ✔️



## Reloading Message ❌

❔ Which you can choose not to do if you want, you can tell me if you want. Because this is not force, but will affect the Stamp of Quality.

I can see that this pack has a tellraw message at installation, which shouldn't be there for this. You should be able to use other methods instead.

# 🔆━━━━━・Not Force・━━━━━🔆
## Common Trait Convention ☑️
## Global Durability ☑️ 
# ⚠━━━━━・Important ・━━━━━⚠
## Custom Model ID ☑️
## Global ignoring tag ❌
- [x] `global.ignore.kill`✔️

- [x] `global.ignore.gui`✔️

- [x] `global.ignore.pos`✔️

- [x]  `global.ignore` ✔️

You don't have a `global.ignore` at `@e` using `score condition`, because score is less clear than `tag` and `nbt`.
Therefore cannot be excluded to not have

```
data\x_core\functions\ticker.mcfunction
data\x_core\functions\scrollbar.mcfunction

data\x_core\functions\rotation_tracking.mcfunction -> Other: `data get entity @s Rotation[X] 1` I see that you put X

data\x_core\functions\manage_eids.mcfunction
data\x_core\functions\manage_attachments.mcfunction
data\x_core\functions\collision_blocking.mcfunction
```

## Namespace Convention ✔️
## Shulker Box Loot Table ☑️
# 🎯━━━━━・Other ・━━━━━🎯
## Something missing ❓
## Bug report 🐞

`data\x_seat\functions\seat_surface.mcfunction`

`@a[tag=x_SEAT_SURFACE_PLAYER,nbt={SelectedItem:{id:"minecraft:hay_bale"}}]` ->Here, the extension warns that this is wrong. 

`data\x_seat\functions\seat.mcfunction` -> `unless entity @s[nbt={SelectedItem:{id:"minecraft:hay_bale"}}]`

Which I think it should be `minecraft: hay_block `

In the `datapack enable x_seat after "file / x_core"` command there will be a problem. The command will not work if the names do not match. Both in the case of a `folder` and a `.zip `

# 📝━━━━━・Note・━━━━━📝
✔️ = Followed
🔆 = Advised to use
❌ = Doesn't follow
❓ =  Doubt / Something missing
☑️ = Not required/Skip
- [ ] = Required -> with ❌ Must do, ✔️ Should do, 🔆 Not force

**Comment by x-2mas** [comment]
Thank you for the review. Files updated [here](https://www.planetminecraft.com/data-pack/s-e-a-t/).

### Changes:
- **Changed `minecraft:hay_bale` to `minecraft:hay_block` in files:** 
    `data\x_seat\functions\seat_surface.mcfunction`
    `data\x_seat\functions\seat.mcfunction`
- **Changed `data get entity @s Rotation[X] 1` to `data get entity @s Rotation[1] 1` in file:**
    `data\x_core\functions\rotation_tracking.mcfunction`


Now about the other changes, can you please explain further 😅?

### Reload Message (_Stamp of Quality Issue_)
There is a tellraw that triggers on reload but it only shows the message to players with the tag `x_LOAD_NOTIFY`. This tag is never applied by the pack anywhere. It has to be manually applied by developers/testers if they wish to see the reload message. So unless the user specifically chooses to see reload messages by manually applying the tag to themselves, they won't see it.

There is also another tellraw message that triggers when users first install the pack (first-install, not reload). This message tells them to reload their world again, as the pack needs to load-in more functionality. The only way to avoid this message is to automatically reload instead of requesting the user to do it. However, calling the /reload function from within the datapack sometimes crashes minecraft!!

### Global Ignoring Tag (_Important Issue_)
Are you saying not to modify user scores if they have the `global.ignore` tag? However, these are scores/objectives that are unique to my pack. Do I need to check for `global.ignore` tag before modifying my own scores?
I have already checked for ignore tags in every command that modifies entity position, rotation, gui, etc. However, is that necessary for every score-check or score-modification too? Even if the scores are purely, only used in my pack?

### Datapack Enabling (_Bug Report_)
I believe you're saying that the command `datapack enable x_seat after "file / x_core"` will cause an issue if the datapack filenames are different. If that is the case, can you suggest the right way to do it? My goal is to make sure that the S.E.A.T (x_seat) datapack only loads after the C.O.R.E (x_core) datapack. What is the right way to code that?

**Comment by x-2mas** [comment]
^ Bump ^

**Comment by EstEarth202** [comment]
# Certified Compatibility ✔️
# Style Guideline Followed 💕
# Final comment:  Cool pack, but I hope this pack will be optimized in the future.

If so, let me suggest, the easiest solution would be to put both.
But this command will use the outermost file name. Therefore, it should be like this
```
datapack enable x_seat after "file/Xmas Labs - C.O.R.E" -> for folder
datapack enable x_seat after "file/Xmas Labs - C.O.R.E.zip" -> for .zip
```

You can now use the [certified banner](https://mc-datapacks.github.io/en/certified_datapacks/index.html) for this datapack. The link to your datapack will also be posted on the #certified-datapacks channel.

**Comment by x-2mas** [comment]
Thank you 😍! 
I'll make the change u suggested and update the pack soon!
