### ISSUE TITLE
Ore Exchange

### ISSUE THREAD

**Issue by JollyChristopher** [mc-datapacks/review-tracker#57]
Project Page: https://www.planetminecraft.com/data-pack/ore-exchange/

**Comment by oOBoomberOo** [comment]
This datapack has been reviewed and determined that it has followed both the official convention and the style guideline.

You can now use the [certified banner](https://mc-datapacks.github.io/en/certified_datapacks/index.html) for this datapack. The link to your datapack will also be posted on the #certified-datapacks channel.

Since I don't your associated discord account to your account, I cannot give you the roles in this case. if you wish to get them, just notify me here.
