### ISSUE TITLE
Stonecutter Damage

### ISSUE THREAD

**Issue by Kore-Development** [mc-datapacks/review-tracker#58]
Project Page: https://www.curseforge.com/minecraft/customization/stonecutter-damage-datapack
(probably have to wait for curseforge moderators)

**Comment by Kore-Development** [comment]
Looks like it was approved by a CurseForge moderator

**Comment by oOBoomberOo** [comment]
This datapack has been reviewed and determined that it has followed both the official convention and the style guideline.

You can now use the [certified banner](https://mc-datapacks.github.io/en/certified_datapacks/index.html) for this datapack. The link to your datapack will also be posted on the #certified-datapacks channel.

Since I don't know the associated discord account to your account, I can't give you the roles in this case. If you wish to get them, just notify me here.

**Comment by Kore-Development** [comment]
@oOBoomberOo Pqtato#3737

**Comment by oOBoomberOo** [comment]
Done, you now have the「Certified Datapacker」and「Style Guideline Follower」roles.
