### ISSUE TITLE
Netherite Fire Resist

### ISSUE THREAD

**Issue by TheSaltyPug** [mc-datapacks/review-tracker#62]
Project Page: https://github.com/TheSaltyPug/Netherite-Fire-Resist

**Comment by oOBoomberOo** [comment]
This datapack has been reviewed and determined that it has followed both the official convention and the style guideline.

You can now use the [certified banner](https://mc-datapacks.github.io/en/certified_datapacks/index.html) for this datapack. The link to your datapack will also be posted on the #certified-datapacks channel.

Since you already have both Certified Datapacker and Style Guideline Follower roles, you will not be given any more roles this time.
