### ISSUE TITLE
Easy Item Descriptions

### ISSUE THREAD

**Issue by BigPapi13** [mc-datapacks/review-tracker#69]
Project Page: https://www.planetminecraft.com/data-pack/easy-item-descriptions-1-17/

**Comment by EstEarth202** [comment]
There are some things I need to ask you first:
You own the Datapack API used in this datapack.
Do you also own this data pack or not?

**Comment by BigPapi13** [comment]
Yes, I own both the API and the pack. This was more or less my first 'test run' of the API. Sorry if that was unclear from the start

**Comment by EstEarth202** [comment]
May I have your Discord `username#0000` too. Because I don't know who you are in the Minecraft Datapacks discord.

Here I recommend that API must also be certified.
In order not to waste time, I recommend that I can fix it for you Just create a repo of this datapack, and I'll fork it out and fix it for you. After it's done, I'll send you a pull request for you to check. If you don't have any questions or don't have any issues, you can merge a pull request, and I'll close this review with a certified announcement for you.

I chose to do this because There may be some communication discrepancies. which may take too long
After I'm done, I'll explain to you at each point why I did it.

**Comment by BigPapi13** [comment]
I'm BigPapi#4914 in the discord.

What you recommended is perfectly fine by me, but if it would make it easier for you if I made a separate issue with the API and a repo with the pack, then I'm able to do that too.
