### ISSUE TITLE
Certification Review Request for Seasonal Calendar by TheWii

### ISSUE THREAD

**Issue by TheWii** [mc-datapacks/review-tracker#7]
Project: https://github.com/TheWii/seasonal-calendar/tree/updated-conventions

**Comment by EstEarth202** [comment]
Seasonal Calendar by @TheWii 

- [Certified Compatibility :x: ] 
- [Stamp of Quality :x: ] 

### Namespace
You use "load" pack for run load, shouldn't do that. You should do it like a tick file.
`#minecraft:load -> thewii:calendar/core/load` 

> Scoreboard SeasonalCalendar

### Additional
If you want stamp, there must not be any messages install on the reload.
For settings and other information, users can type `/trigger` themselves.

**Comment by oOBoomberOo** [comment]
[Re-worded]
Seasonal Calendar by @TheWii 
- Certified Compatibility ❌ 
- Stamp of Quality ❌ 

This datapack embedded the [LanternMC/load](https://github.com/LanternMC/Load) library which uses the scoreboard `load` that doesn't follow any namespacing scheme, this still counts as violating namespace convention even if it's from a library datapack.

Additionally, If you want a "Stamp of Quality" you must follow the Style Guideline but you failed to do so here because the datapack sends a message on reloading the world. This isn't a critical error and you can choose to ignore them if you want.

**Comment by TheWii** [comment]
#### Namespace

Regarding [LanternMC/load](https://github.com/LanternMC/Load) conflict problems: I moved the library directory **load:** to **thewii:load/** and renamed the scoreboard objective from **load** to **thewii.load**.

#### Additional

Removed all the messages when reloading the world to follow the Style Guideline.

**Comment by EstEarth202** [comment]
Seasonal Calendar by @TheWii

- [Stamp of Quality :two_hearts: ]
