### ISSUE TITLE
Disenchanting

### ISSUE THREAD

**Issue by TheSaltyPug** [mc-datapacks/review-tracker#70]
Project Page: [https://github.com/TheSaltyPug/Disenchanting](https://github.com/TheSaltyPug/Disenchanting)

**Comment by EstEarth202** [comment]
This pack has been `Certified + Styte Guideline`.
But
Which is like your other pack, I fixed some points.

But if you ask why I use predicate
because I have tried debug profiling several times.
I found this method reduces the percentage cost of `execute as @` pending at any item drop.
![opera_sqNdGhDtbf](https://user-images.githubusercontent.com/66269767/125139161-3e080d80-e13a-11eb-8920-5a0e5175096b.png)
![opera_DvU1wOVtOR](https://user-images.githubusercontent.com/66269767/125139169-4102fe00-e13a-11eb-8382-346ef4be941a.png)
![opera_dXSxcotECs](https://user-images.githubusercontent.com/66269767/125139571-f6ce4c80-e13a-11eb-8d72-00af3b58bcee.png)
![opera_geQnnCIDeT](https://user-images.githubusercontent.com/66269767/125139381-a22ad180-e13a-11eb-9e71-fb65c531921a.png)

If you don't have any questions or issues, you can merge pull request and let me know in the comments to close this review.
Or, as always, you can reject this as you wish. And I'll close the review for you.

**Comment by TheSaltyPug** [comment]
Thank you again, Est. Merged changes upstream. You may close with the correct tags.

**Comment by EstEarth202** [comment]
# Certified Compatibility ✔️
# Style Guideline 💕 
*Don't forget to tell the user how to uninstall. 

You can now use the [certified banner](https://mc-datapacks.github.io/en/certified_datapacks/index.html) for this datapack. The link to your datapack will also be posted on the #certified-datapacks channel.
Since you already have both Certified Datapacker and Style Guideline Follower roles, you will not be given any more roles this time.

### Final comment: Useful and LMAO Datapack reviewer @EstEarth202. :thumbsup:.
PS. Nice to help and thanks too.
