### ISSUE TITLE
Twerking

### ISSUE THREAD

**Issue by TheSaltyPug** [mc-datapacks/review-tracker#71]
Project Page: [https://github.com/TheSaltyPug/Twerking](https://github.com/TheSaltyPug/Twerking)

**Comment by EstEarth202** [comment]
So in order not to waste time, I have fixed it for you, in fork
To reduce explanations that may be lengthy and communication may be inaccurate.
So I'm doing this to make it easier. If you don't understand, feel free to ask me.

- If asked why remove `!global.ignore`

Because `this tag does not apply to player-only selectors (@a, @e[type=player], @p, etc.)`

- If you ask me why I use `schedule function tsp:twerking/main 1t`

Because it works the same as `tick.json`.
And it's easy to uninstall too, just `schedule clear tsp:twerking/main`.
Because if you use `datapack disable "file/Twerking"`
If the user installs a `.zip`, it won't work. And the file name must match as well.
Even if you can do like this
```
datapack disable "file/<name>"
datapack disable "file/<name>.zip"
```
But if file name is `Twerking_v1.0.0.zip`.
Either install it as a `.zip` or `extract to folder` it won't work.
```
<name>.zip -> /data
<name>/data
```
It's a headache to do this, which I see as unnecessary
So I chose the easier way.

If asked why `minecraft/.../load.json` and then do
```
{
     "values": [
          "tsp:twerking/setup",
          "tsp:twerking/main"
     ]
}
```
Because you don't need to call nested files like this.
`minecraft/load.json` -> `tsp/twerking/load.json` -> `main/setup.mcfunction`
instead of this
`minecraft/load.json` -> `main/setup.mcfunction `

The fork review I fixed and a few other fixed issues for you is the version that has certified + style guideline.
If you don't have any questions or issues, you can merge pull request and let me know in the comments to close this review.
Or, as always, you can reject this as you wish. And I'll close the review for you.
Or you can fix it yourself. Let's just think I'm just giving you a fixed example.

### Hope this will be helpful to you, more or less, as a Datapack Reviewer.

**Comment by TheSaltyPug** [comment]
Thanks for the updates, merged upstream. Thanks Estt!

**Comment by TheSaltyPug** [comment]
(not-so-quietly reopening this because I realize you need to close it with a tag)

**Comment by EstEarth202** [comment]
# Certified Compatibility ✔️
# Style Guideline 💕
*Don't forget to tell the user how to uninstall. 

You can now use the [certified banner](https://mc-datapacks.github.io/en/certified_datapacks/index.html) for this datapack. The link to your datapack will also be posted on the #certified-datapacks channel.
Since you already have both Certified Datapacker and Style Guideline Follower roles, you will not be given any more roles this time.

### Final comment: Not bad and LMAO Datapack reviewer @EstEarth202. :thumbsup:.
PS. And again nice to help and thanks too.
