### ISSUE TITLE
Miniblock Traders

### ISSUE THREAD

**Issue by maxheyn** [mc-datapacks/review-tracker#82]
Project Page: <https://github.com/maxheyn/miniblock_traders>

**Comment by oOBoomberOo** [comment]
A bounty of $10 has been added to this review. You will be rewarded if you choose to review this datapack.

*Keep in mind that I will be expecting a high-quality review with this bounty.*

**Comment by EstEarth202** [comment]
- **Request review:** If you have, please include every website where your datapack is published. It doesn't have to be just GitHub or Planetminecraft. And if you're on the Minecraft Datapacks discord server, add your `Username#0000` as well.
   - **Review type:** please also specify the type of review you require.
     - Certified Compatibility ✅ Only
     - Certified Compatibility ✅ + Style Guideline Followed 📚 (Optional)

**Comment by maxheyn** [comment]
**Published Websites**
- https://www.planetminecraft.com/data-pack/miniblock-traders/
- https://github.com/maxheyn/miniblock_traders

**Discord User**
- Maxypoo#4327

**Review Type**
- Just Certified Compatibility ✅

**Comment by EstEarth202** [comment]
# Certified Compatibility ⚠

# ⚠━━━━━・Important ・━━━━━⚠

## Global ignoring tag ⚠

- [ ] **Datapack Uninstallation ⚠**
- Your villagers are the content of your datapack and have the global ignoring. It can affect other datapacks if you don't clear it when uninstallation. 
  - Because there are some datapacks that will first check if a global ignoring entity exists in that area or not before running.

## Namespace Convention ✅

And again, be sure to read the instructions in the previous review and applied.

## Bug report 🐞
- data\miniblock_traders\functions\creative\give_conversion_chest.mcfunction
  - You need to include `' '` in between `" "`. ⇒ `give @p minecraft:chest{display:{Lore:['"Miniblock Traders Conversion Chest"']}`

## Additional clarifications
**1. Warnings ⚠**

**Datapack Advancement**
- You shouldn't put these folders into `global/advancements`, but should be inside your datapack.
  - `data\global\advancements\items`
  - `data\global\advancements\traders`
  
 **Many repeat execute selector with the same condition.**
 - data\miniblock_traders\functions\main.mcfunction ⇒ `execute as @e[type=minecraft:villager,tag=!global.ignore] at @s`
   - You can do this.
```mcfunction
#> miniblock_traders:main
execute as @e[type=minecraft:villager,tag=!global.ignore] at @s run function miniblock_traders:villager

#> miniblock_traders:villager
execute if entity @e[type=item,nbt={Item:{tag:{tag:mt_apple}}},distance=..0.5]
execute if entity @e[type=item,nbt={Item:{tag:{tag:mt_sapling}}},distance=..0.5]
#
#
#
```
  
 **2. Other**
 
- `data\miniblock_traders\functions\traders\ritualist.mcfunction` ⇒ `"obfuscated":"true"`
  - You should remove the `" "` from boolean. 
- `data\miniblock_traders\functions\traders` ⇒ particle commands
  - It was unnecessary to have `execute at @s run`.

**Comment by maxheyn** [comment]
Thank you, I will get to this soon. Just wanted to post a comment here acknowledging that I see this.

**Comment by maxheyn** [comment]
Closing as I am currently not working on this.
