### ISSUE TITLE
Potion Launcher

### ISSUE THREAD

**Issue by oOBoomberOo** [mc-datapacks/review-tracker#9]
Project Page: https://github.com/oOBoomberOo/potion-launcher/releases

**Comment by EstEarth202** [comment]
Potion Launcer by @oOBoomberOo 

- Certified Compatibility:heavy_check_mark:
- Datapack reviewer @EstEarth202 approved. :thumbsup: 

### Additional  (It does not affect the review, you can skip this.)

- [ ] Should also write about how to uninstall for the user

**I can see that it is a bag, it should be a storage. Or whichever you use new traits for your own use.**
- [ ] Potion Bug's ctc, I think it can be add. "tool/storage"

**Since it is a weapon and made of iron.**
- [ ] Potion Launcher's ctc, I think it can be add. "tool/weapon" & "metal/iron"
